# Netlify Configuration File
[build]
  publish = "."

# Disable Netlify Drawer / Feedback tool
[context.production.environment]
  NETLIFY_DRAWER = "false"

[context.deploy-preview.environment]
  NETLIFY_DRAWER = "false"

[context.branch-deploy.environment]
  NETLIFY_DRAWER = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
